Repository ballyalley-o/tccp, pull requests merged in 2024-04, with the labels that each got.

#109 TCCPISSUE83-register-form-rhf-mutation: Register form implementation of RHF
  src/component/form/form-field/form-button-redir.tsx
  src/component/form/form-field/form-field.tsx
  src/component/form/form-field/github-field.tsx
  src/component/form/form-field/index.ts
  src/component/form/index.ts
  src/component/form/upload-field/upload-field.tsx
  src/page/auth/log-in/log-in.tsx
  src/page/auth/register/register-layout.tsx
  src/page/auth/register/register.tsx
  src/page/auth/register/use-register.tsx
  src/route/path.ts
  src/section/auth/constant.ts
  src/store/slice/auth/endpoint.ts
  src/store/slice/index.ts
  src/types/global.d.ts
Labels: priority 2, refactor

#111 Refactor form components and update authentication state
  src/component/form/form-field/form-field.tsx
  src/component/form/form-field/index.ts
  src/component/form/form-field/password-field.tsx
  src/component/form/form-field/role-field.tsx
  src/component/form/index.ts
  src/component/snack/alert.tsx
  src/constant/aria.ts
  src/constant/index.ts
  src/constant/key.ts
  src/constant/local-storage.ts
  src/page/auth/log-in/log-in.tsx
  src/page/auth/register/index.ts
  src/page/auth/register/register-layout.tsx
  src/page/auth/register/register.tsx
  src/page/auth/register/use-register.tsx
  src/section/auth/constant.ts
  src/store/slice/auth/auth.ts
  src/store/store.ts
  src/theme/palette.ts
  src/types/global.d.ts
Labels: priority 2, refactor, incomplete

#114 TCCPISSUE83-register-form-rhf-mutation: Fix login and register issues
  src/auth/auth-provider.tsx
  src/component/form/form-field/form-field.tsx
  src/component/form/form-field/role-field.tsx
  src/component/navbar/account-popover.tsx
  src/component/navbar/app-appbar.tsx
  src/constant/key.ts
  src/constant/local-storage.ts
  src/constant/response.ts
  src/page/auth/log-in/log-in.tsx
  src/page/auth/register/register-layout.tsx
  src/page/auth/register/register.tsx
  src/page/auth/register/use-register.tsx
  src/schema/auth.ts
  src/schema/index.ts
  src/section/auth/constant.ts
  src/store/root-reducer.ts
  src/store/slice/auth/auth.ts
  src/store/slice/auth/endpoint.ts
  src/store/store.ts
  src/types/global.d.ts
  vite.config.ts
Labels: priority 1, solved

#115 TCCPISSUE83-register-form-rhf-mutation: Fix authentication bugs and refactor register form
  package-lock.json
  package.json
  src/auth/auth-provider.tsx
  src/component/form/form-field/form-button-redir.tsx
  src/component/form/form-field/form-field.tsx
  src/component/form/form-field/github-field.tsx
  src/component/form/form-field/index.ts
  src/component/form/form-field/password-field.tsx
  src/component/form/form-field/role-field.tsx
  src/component/form/index.ts
  src/component/form/upload-field/upload-field.tsx
  src/component/navbar/account-popover.tsx
  src/component/navbar/app-appbar.tsx
  src/component/snack/alert.tsx
  src/constant/aria.ts
  src/constant/index.ts
  src/constant/key.ts
  src/constant/local-storage.ts
  src/constant/response.ts
  src/page/auth/log-in/log-in.tsx
  src/page/auth/register/index.ts
  src/page/auth/register/register-layout.tsx
  src/page/auth/register/register.tsx
  src/page/auth/register/use-register.tsx
  src/route/path.ts
  src/schema/auth.ts
  src/schema/index.ts
  src/section/auth/constant.ts
  src/store/root-reducer.ts
  src/store/slice/auth/auth.ts
  src/store/slice/auth/endpoint.ts
  src/store/slice/index.ts
  src/store/store.ts
  src/theme/palette.ts
  src/types/global.d.ts
  vite.config.ts
Labels: priority 1, solved, refactor

#118 Fix Auth State in AppBar
  README.md
  src/component/navbar/app-appbar.tsx
  src/page/auth/log-in/log-in.tsx
Labels: bug, solved

#120 Feature: Implement Snackbar hook
  package-lock.json
  package.json
  src/app.tsx
  src/component/navbar/account-popover.tsx
  src/config/icon-directory.ts
  src/hook/index.ts
  src/hook/use-snack/index.ts
  src/hook/use-snack/style.tsx
  src/hook/use-snack/use-snack.tsx
  src/page/auth/log-in/log-in.tsx
Labels: feat, priority 2

#121 Feat/TCCP117-feature-snackbar-hook: Implement Snackbar hook and related changes
  src/auth/auth-provider.tsx
  src/config/icon-directory.ts
  src/constant/response.ts
  src/constant/size.ts
  src/hook/index.ts
  src/hook/use-snack/index.ts
  src/hook/use-snack/style.tsx
  src/hook/use-snack/use-snack.tsx
  src/page/auth/log-in/log-in.tsx
  src/page/dashboard/dashboard.tsx
  src/theme/palette.ts
  src/theme/theme.ts
  src/theme/typography.ts
  src/types/global.d.ts
Labels: feat, priority 2, refactor

#122 Feat/TCCP117-feature-snackbar-hook: Implement Snackbar hook
  package-lock.json
  package.json
  src/app.tsx
  src/auth/auth-provider.tsx
  src/component/navbar/account-popover.tsx
  src/config/icon-directory.ts
  src/constant/response.ts
  src/constant/size.ts
  src/hook/index.ts
  src/hook/use-snack/index.ts
  src/hook/use-snack/style.tsx
  src/hook/use-snack/use-snack.tsx
  src/page/auth/log-in/log-in.tsx
  src/page/dashboard/dashboard.tsx
  src/theme/palette.ts
  src/theme/theme.ts
  src/theme/typography.ts
  src/types/global.d.ts
Labels: feat, priority 2, refactor

#124 Other/TCCP14-redux--user-slice: Fix Redux and View Issues in User Slice
  src/auth/auth-guard.tsx
  src/auth/index.ts
  src/component/menu-popover/get-position.ts
  src/component/motion/motion-lazy-container.tsx
  src/component/navbar/account-popover.tsx
  src/component/navbar/util/option.tsx
  src/constant/routing/routing.ts
  src/page/auth/account/user-account.tsx
  src/page/auth/index.ts
  src/page/auth/register/register.tsx
  src/page/bootcamp/bootcamp.tsx
  src/page/fallback/fallback.tsx
  src/page/index.ts
  src/route/element.tsx
  src/route/index.tsx
  src/route/path.ts
  src/section/bootcamp/bootcamp.tsx
  src/section/bootcamp/dashboard-value.tsx
  src/store/reducer/bootcamp.ts
  src/store/reducer/index.ts
  src/store/slice/auth/endpoint.ts
  src/store/slice/bootcamp/endpoint.ts
  src/store/slice/bootcamp/index.ts
  src/store/slice/index.ts
  src/store/slice/user/endpoint.ts
  src/store/slice/user/index.ts
  src/theme/palette.ts
  src/theme/style/main.ts
  src/theme/theme.ts
  src/types/global.d.ts
Labels: priority 1

#125 #14 Redux User Slice and Init User Account View
  public/asset/background/dot-matrix.svg
  public/asset/background/pattern.svg
  src/auth/auth-guard.tsx
  src/auth/index.ts
  src/component/menu-popover/get-position.ts
  src/component/motion/motion-lazy-container.tsx
  src/component/navbar/account-popover.tsx
  src/component/navbar/util/option.tsx
  src/constant/response.ts
  src/constant/routing/routing.ts
  src/page/auth/account/user-account.tsx
  src/page/auth/index.ts
  src/page/auth/register/register.tsx
  src/page/bootcamp/bootcamp.tsx
  src/page/fallback/fallback.tsx
  src/page/index.ts
  src/route/element.tsx
  src/route/index.tsx
  src/route/path.ts
  src/section/bootcamp/bootcamp.tsx
  src/section/bootcamp/dashboard-value.tsx
  src/store/reducer/bootcamp.ts
  src/store/reducer/index.ts
  src/store/slice/auth/endpoint.ts
  src/store/slice/bootcamp/endpoint.ts
  src/store/slice/bootcamp/index.ts
  src/store/slice/index.ts
  src/store/slice/user/endpoint.ts
  src/store/slice/user/index.ts
  src/theme/palette.ts
  src/theme/style/main.ts
  src/theme/theme.ts
  src/types/global.d.ts
Labels: priority 1

#131 Fix font and user account page issues
  public/asset/background/wavey.svg
  src/_mock/bootcamp.ts
  src/auth/utility.ts
  src/component/avatar/avatar-default.tsx
  src/component/button/button-animated.tsx
  src/component/navbar/app-appbar.tsx
  src/config/asset-directory.ts
  src/config/icon-directory.ts
  src/page/auth/account/user-account.tsx
  src/page/auth/register/register-layout.tsx
  src/page/bootcamp/bootcamp.tsx
  src/store/slice/api.ts
  src/store/slice/auth/endpoint.ts
  src/theme/css/index.css
  src/theme/style/main.ts
  src/theme/theme.ts
  src/types/global.d.ts
  src/util/index.ts
  src/util/time.ts
Labels: priority 1

#132 User account page issues and font family update
  public/asset/background/wavey.svg
  src/_mock/bootcamp.ts
  src/auth/utility.ts
  src/component/avatar/avatar-default.tsx
  src/component/button/button-animated.tsx
  src/component/navbar/app-appbar.tsx
  src/config/asset-directory.ts
  src/config/icon-directory.ts
  src/page/auth/account/user-account.tsx
  src/page/auth/register/register-layout.tsx
  src/page/bootcamp/bootcamp.tsx
  src/store/slice/api.ts
  src/store/slice/auth/endpoint.ts
  src/theme/css/index.css
  src/theme/style/main.ts
  src/theme/theme.ts
  src/types/global.d.ts
  src/util/index.ts
  src/util/time.ts
Labels: priority 1

#133 Review some and clean up in the interfaces
  src/component/avatar/avatar-default.tsx
  src/component/avatar/avatar.tsx
  src/constant/index.ts
  src/constant/typography.ts
  src/types/global.d.ts
Labels: review, clean-up

#134 Review some and clean up in the interfaces (#133)
  src/component/avatar/avatar-default.tsx
  src/component/avatar/avatar.tsx
  src/constant/index.ts
  src/constant/typography.ts
  src/types/global.d.ts
Labels: review, clean-up

#135 [BUG] Fix mapping key issue in AnimatePresence component
  src/component/navbar/account-popover.tsx
  src/hook/use-snack/use-snack.tsx
Labels: solved

#138 Redux Course Slice added
  src/constant/routing/routing.ts
  src/page/dashboard/dashboard.tsx
  src/route/path.ts
  src/store/root-reducer.ts
  src/store/slice/auth/endpoint.ts
  src/store/slice/bootcamp/endpoint.ts
  src/store/slice/course/endpoint.ts
  src/store/slice/course/index.ts
  src/store/slice/index.ts
  src/types/global.d.ts
Labels: priority 1

#139 Redux Course Slice added (#138)
  src/constant/routing/routing.ts
  src/page/dashboard/dashboard.tsx
  src/route/path.ts
  src/store/root-reducer.ts
  src/store/slice/auth/endpoint.ts
  src/store/slice/bootcamp/endpoint.ts
  src/store/slice/course/endpoint.ts
  src/store/slice/course/index.ts
  src/store/slice/index.ts
  src/types/global.d.ts
Labels: priority 1

#151 Redux Course Slice added (#138)
  src/page/bootcamp/bootcamp.tsx
Labels: priority 2, enhancement

#156 Refactor Bootcamp tile and Bootcamp components
  src/component/form/form-field/form-field.tsx
  src/component/setting/style.tsx
  src/config/category.ts
  src/config/icon-directory.ts
  src/config/index.ts
  src/constant/aria.ts
  src/constant/button.ts
  src/constant/component.ts
  src/constant/index.ts
  src/constant/key.ts
  src/constant/label.ts
  src/constant/placeholder.ts
  src/constant/sx.ts
  src/constant/variant.ts
  src/page/auth/account/user-account.tsx
  src/page/course/course.tsx
  src/section/bootcamp/bootcamp-card.tsx
  src/section/bootcamp/bootcamp-career.tsx
  src/section/bootcamp/index.ts
  src/section/course/course-card.tsx
  src/section/dashboard/dashboard-bootcamp-rd.tsx
  src/section/dashboard/dashboard-bootcamp-tile.tsx
  src/section/dashboard/index.ts
  src/section/dashboard/option.tsx
  src/theme/style/main.ts
  src/types/global.d.ts
  src/util/asset-loc.ts
  src/util/index.ts
Labels: priority 1, solved, refactor
